    [theme]
    base="light"
    primaryColor="#7a3c8b"
    # You can uncomment and set other colors if desired
    # backgroundColor="#f0f2f6"
    # secondaryBackgroundColor="#e6eaf1"
    # textColor="#31333F"
    # font="sans serif"